### ISSUE TITLE
Python 3.6 doesn't work with Lambda Function via Serverless App Repository (SAR)

### ISSUE THREAD

**Issue by mherzog01** [aws-samples/aws-sagemaker-ground-truth-recipe#3]
I tried to create the Lambda functions in this repository using the Serverless App Repository (SAR) by following the instructions in https://docs.aws.amazon.com/sagemaker/latest/dg/sms-custom-templates-step3-lambda-create.html.  CloudFormation reported an error:

```
The runtime parameter of python3.6 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (python3.9) while creating or updating functions.
```

I see that Python3.6 is specified in ```template.yaml```.

It would be nice to use this SAR as opposed to creating Lambda functions and associated objects manually.  What can be done to address this failure?

**Comment by aws-mmanwani** [comment]
Thank you for reporting the issue!

It has been fixed. See commit bd0db33015748b389e268f4c75985c0b04de502d.
